[package]
name = "taskchampion-lib"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
taskchampion = { git = "https://github.com/GothenburgBitFactory/taskchampion.git", branch = "main" }
cxx = "1.0.124"

[build-dependencies]
cxx-build = "1.0"
